name: PR dependencies

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited, closed, reopened]
  pull_request:
    types: [synchronize]
  merge_group:

permissions: {}

jobs:
  check_dependencies:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: gregsdennis/dependencies-action@7c996e243cd81253305ae46a4799b1e4b65bf1fb # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
